name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Run Tests
        run: npm run wdio
      - name: Upload WDIO logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: wdio-logs
          path: ${{ github.workspace }}/test/logs/
          if-no-files-found: ignore
          retention-days: 7